#!/bin/bash

# procedura per il download dei dati da server sisifo
#
#
# Uso: getdata anno
#

REMOTE=acquisti@sisifo.arcetri.inaf.it

if [ -z "$1" ]
then
	echo "Manca specifica anno"
        exit
fi
rsync -vrpz $REMOTE:v5/data/$1 data/
