#!/bin/bash

# Procedura per commutare versione corrente
#
# NOTA: la pricedura è stata modificata il 6/3/2024 per consentire
#       la gestione della versione 5 del codice che utilizza i link
#       bin5 e files5 al posto di bin e files. La versione corrente
#       rimane fissata a 4.10
#
# La procedura deve essere lanciata dalla home directory
# del programma acquisti, e si limita a modificare i link
# di nome "bin" e "files" per puntare alla versione richiesta

# NOTA: occorre prima interrompere i servizi
#
#     systemctl stop acquisti5
#     systemctl stop manageldap5
#

VERSION=$1

bin_target=bin-$VERSION
files_target=files-$VERSION

if [ ! \( -d $bin_target -a -d $files_target \) ]; then
   echo
   echo "Cannot found release: $VERSION"
   exit 1
fi

rm -f bin5
ln -s $bin_target bin5
rm -f files5
ln -s $files_target files5

echo
echo "Enabled version:  $VERSION"
